### ISSUE TITLE
您好，想请问下这个有进行提取特征的操作嘛？mobilenetv2.pth.tar这个的作用是啥呀，多谢您啦

### ISSUE THREAD

**Issue by InkstarONE** [Maicius/NIMA4Images#1]
您好，想请问下这个有进行提取特征的操作嘛？mobilenetv2.pth.tar这个的作用是啥呀，多谢您啦

**Comment by Maicius** [comment]
你好，这个模型是google推出的，我只是用他们的预训练模型做了一下实验，模型的实现细节并不清楚，论文已经在readme中给出了，有兴趣的话可以阅读一下。mobilenetv2.pth.tar是他们预训练的模型地址。

**Comment by InkstarONE** [comment]
感谢  原来是这样子呀
